### ISSUE TITLE
The cursor will be placed in Show/Hide when flagging the answer

### ISSUE THREAD

**Issue by CarolHayes** [designwall/dw-question-answer#120]
![cusor-when-hovering](https://cloud.githubusercontent.com/assets/6157366/4501769/c170f6c4-4ab4-11e4-8354-c32aa90e59dd.png)

**Comment by anna2810** [comment]
Hi CarolHayes,
Thank you for noticing us. We do really appreciate your help.
This feature had been disabled from DW Q&A 1.4.0, we will add this feature in the upcoming version. Please update the DW Q&A and continue using it.
If there is any more issue with the plugin, please do not hesitate to get back to us. It encourages us a lot.
