### ISSUE TITLE
Setting to use recaptcha with ssl

### ISSUE THREAD

**Issue by chrillep** [designwall/dw-question-answer#123]
recaptcha_get_html ($pubkey, $error = null, $use_ssl = true)

**Comment by anna2810** [comment]
Hi Chrillep,

Thank you for noticing us. We do really appreciate your help.

We have noted the issue you mentioned above. It will be fixed in the next version of DW Question & Answer. 

If there is any more issue with the plugin, please do not hesitate to get back to us. It encourages us a lot.
