### ISSUE TITLE
Caching

### ISSUE THREAD

**Issue by eurobank** [designwall/dw-question-answer#127]
Not sure if this is something related to the plugin, still if i use ANY caching plugin, pages are not updated.

Pages that contain the DW Questions AND the Home page with the DW widget. I had to disable caching to some pages to make this work.

Thanks

**Comment by anna2810** [comment]
Hi Eurobank,

Thank you for getting in touch with us.

Are you currently using any cache plugin?


If there is any more issue with the plugin, please do not hesitate to get back to us. It encourages us a lot.
