### ISSUE TITLE
As contributor, author of the answer draft can not edit the answer draft

### ISSUE THREAD

**Issue by CarolHayes** [designwall/dw-question-answer#132]
As contributor, author of the answer draft can not edit the answer draft
http://prntscr.com/59wsaz

**Comment by anna2810** [comment]
Hi CarolHayes,
Thank you for noticing us. We do really appreciate your help.

This feature has been disabled in DW Q&A 1.4.0 and we will add this feature in the upcoming version.
Please update the DW Q&A and continue using it.

If there is any more issue with the plugin, please do not hesitate to get back to us. It encourages us a lot.
