### ISSUE TITLE
List questions like a table of contents by category and subcategory?

### ISSUE THREAD

**Issue by stevepowell99** [designwall/dw-question-answer#150]
I would like the question list page to list questions by category and subcategory, like a table of contents?

```
QUESTION LIST

Main Category 1
  Subcategory a
    is foo bar? ....
    is bar foo? ....
  Subcategory b
    asdf asdf ...
    ...
Main Category 2
...
```

I might pay a bounty for this!

**Comment by anna2810** [comment]
Hi Stevepowell99,

Thank you for letting us know your issue.

Please reach us at hi@designwall.com or read more about our custom work services here: https://www.designwall.com/wordpress/services/ for a further assistance.

Don't worry. We're here to help.
