### ISSUE TITLE
auto follow own questions

### ISSUE THREAD

**Issue by stevepowell99** [designwall/dw-question-answer#152]
I assumed the default setting would be for contributors to automatically follow their own questions and answers but this does not seem to be the case - is there a hack for this?

**Comment by anna2810** [comment]
Hi Stevepowell99,

Thank you for noticing us. We do really appreciate your help.

This feature had been added in DW Q&A 1.4.3. Please keep updating the plugin and continue using it.

If there is any more issue with the plugin, please do not hesitate to get back to us. It encourages us a lot.
