### ISSUE TITLE
WP_Widget is obsolete

### ISSUE THREAD

**Issue by CybMeta** [designwall/dw-question-answer#163]
I see that you have updated the code of widgets to not use PHP 4 constructors, but you have fixed only the child class constructor, note that you are still using `$this->WP_Widget`, which is the PHP4-style constructor of WP_Widget class and which is deprecated from WP 4.3. I summited some pull requests with both child and parent classes constructor calls fixed but they was ignored (for example [this one](https://github.com/designwall/dw-question-answer/pull/161/files)).

I suggest to fix these issues by using `parent::__construct()` (or any other valid syntax) instead of `$this->WP_Widget` and, for the future, you could consider taken into account contributions from others if applicable.

**Comment by bighug** [comment]
thank CybMeta very much, this issue was fixed in 1.3.4 released. I changed directory and file structure of the widgets files so i didn't merge your request but the functions was fixed like your suggestion. Thank again and hope you to continue to contribute with us.

**Comment by CybMeta** [comment]
I understand. Thank you.

Happy new year!!
