### ISSUE TITLE
Unable to ask email addresses of anonymous users (who asked the question) for notifying them if answers are available

### ISSUE THREAD

**Issue by tdgunes** [designwall/dw-question-answer#181]
Hello there,

For the use case, where a single person answers questions of the anonymous users, I couldn't find any option in the plugin to notify users who asked questions. I think it would be great if I could ask for their email address and whenever I answer their questions, I could send answers to their mails. Therefore, they wouldn't be required to go to question list page to check whether an answer is posted or not.

And of course, thanks for this awesome plugin.

**Comment by anna2810** [comment]
Hi Tdgunes,

Thank you for noticing us. We do really appreciate your help.

We have noted the issue you mentioned above. It will be fixed in the next version of DW Question & Answer. 

If there is any more issue with the plugin, please do not hesitate to get back to us. It encourages us a lot.
