### ISSUE TITLE
Users can dismiss alert: "To support this plugin and get more features, upgrade to DW Question & Answer Pro →"

### ISSUE THREAD

**Issue by s3w47m88** [designwall/dw-question-answer#185]
After activation the following message appears at the top of the page across all pages but cannot be dismissed: "To support this plugin and get more features, upgrade to DW Question & Answer Pro →"

**Comment by anna2810** [comment]
Hi S3w47m88,

This issue has been fixed in DW Q&A 1.4.3.3. Please update the DW Q&A and continue using it.

If there is any more issue with the plugin, please do not hesitate to get back to us. It encourages us a lot.
