### ISSUE TITLE
Undo / Remove Vote

### ISSUE THREAD

**Issue by bruffridge** [designwall/dw-question-answer#189]
A user should be able to see what they voted on questions and answers by coloring the up or down arrow some non grey color based on their vote. Clicking on the colored arrow should remove the vote. Currently if someone votes up or down, they can not undo their vote only vote in the opposite direction.

**Comment by anna2810** [comment]
Hi Bruffridge

Thanks again for noticing us. We do really appreciate your help.

We have noted the issue you mentioned above. It will be fixed in the next version of DW Question & Answer. 

If there is any more issue with the plugin, please do not hesitate to get back to us. It encourages us a lot.
