### ISSUE TITLE
Don't allow users to vote on own questions and answers

### ISSUE THREAD

**Issue by bruffridge** [designwall/dw-question-answer#190]
Remove the ability for users to vote on their own questions and answers. Maybe make this an option in dwqa settings page.

**Comment by anna2810** [comment]
Hi Bruffridge,

Thank you for noticing us. We do really appreciate your help.

We have noted the issue you mentioned above. It will be fixed in the next version of DW Question & Answer. 

If there is any more issue with the plugin, please do not hesitate to get back to us. It encourages us a lot.
