### ISSUE TITLE
Can't deactivate the plugin

### ISSUE THREAD

**Issue by sohaeb** [designwall/dw-question-answer#191]
Error I get when trying to deactivate the plugin:

> Fatal error: Call to a member function remove_cap() on a non-object in /home/uwindsor/public_html/wp-content/plugins/dw-question-answer/inc/Permission.php on line 254

I tried uninstalling, nothing happened. Its still there in the plugins page

**Comment by anna2810** [comment]
Hi Sohaeb,

Thank you for noticing us. We do really appreciate your help.

We have noted the issue you mentioned above. It will be fixed in the next version of DW Question & Answer. 

If there is any more issue with the plugin, please do not hesitate to get back to us. We're here to help.
