### ISSUE TITLE
load_plugin_textdomain() position maybe not suiteable

### ISSUE THREAD

**Issue by mangobowl** [designwall/dw-question-answer#192]
As the i18n guide metioned in [I18n_for_WordPress_Developers](https://codex.wordpress.org/I18n_for_WordPress_Developers),
**load_plugin_textdomain()** function should be called as early as the plugin_loaded action.

so, the **load_plugin_textdomain()** function called in **dw-question-answer.php** line 90 is not suiteable, which makes translation of menu(and top navbar) not work.

Maybe it shoule be put before **DWQA_Posts_Question()** instantiation(line 44)? I test that it works.

**Comment by anna2810** [comment]
Hi Mangobowl,

Thank you for noticing us. We do really appreciate your help.

We have noted the issue you mentioned above. It will be fixed in the next version of DW Question & Answer. 

If there is any more issue with the plugin, please do not hesitate to get back to us. It encourages us a lot.
