### ISSUE TITLE
Wrong permalink is saved in database for post type dwqa-answer

### ISSUE THREAD

**Issue by PrafullaKumarSahu** [designwall/dw-question-answer#194]
The guid column stores the permalink something like  http://localhost/mysite/dwqa-answer/answer-for-mr-abc/  but this url display 404  error. it should be the link to question page something like  http://localhost/mysite/questions/question_id#answer_id .

**Comment by PrafullaKumarSahu** [comment]
if I am logged in it redirects to http://localhost/mysite/questions/question_id but if not logged in displays 404 no confirmed but it seems to be a bug.

**Comment by anna2810** [comment]
Hi PrafullaKumarSahu,

Thank you for noticing us. We do appreciate it.
We'll check and fix the bug as soon as possible.
If you encounter any problem, please do not hesitate to get back to us. We're here to help you.

**Comment by PrafullaKumarSahu** [comment]
thank you for your reply, for now I am too working on it so if I will notice any other issue, I will surely post it by creating different threads . for now if possible reply me on wordpress plugin support section, I need your guidance there.

**Comment by anna2810** [comment]
Okay buddy. :)
