### ISSUE TITLE
URL to answer redirecting to wired page

### ISSUE THREAD

**Issue by PrafullaKumarSahu** [designwall/dw-question-answer#195]
http://localhost/mysite/answer/?user=user_name&sort=answers
http://localhost/mysite/answer/?user=user_name

these urls redirected question page for which the user_name has answered first .

**Comment by anna2810** [comment]
Hi PrafullaKumarSahu,

Thanks for writing in. However, please tell us what you'd want us to assist. We'll find ways to help you.

**Comment by PrafullaKumarSahu** [comment]
thank you for your reply , I solved this by extending your plugin to all way I need, from search to templates everything and posted the questions and answers on your wordpress plugin support forum .

**Comment by anna2810** [comment]
You're welcome, my friend. :smiley:
