### ISSUE TITLE
The visual editor does not appear on specific mobile devices

### ISSUE THREAD

**Issue by qoncer** [designwall/dw-question-answer#233]
Hi,

We just discovered a very strange bug with TinyMCE used in this plugin. When visiting the "Ask question" page, the visual editor is gone on specific android devices (Oneplus 7 Pro). The element which should contain the formating-buttons is totally gone and as far as I know, the file "/assets/js/code-edit-button.js" isn't being loaded.

Note that it works great on all other devices, just not Oneplus 7 Pro with Chrome as the browser. Note that we have tried resetting and updating the phone, but with no success. Now we're afraid this might affect other phones as well which we cannot test.

Regards
William

**Comment by williamfridh** [comment]
We ended up using another solution. Hope this gets fixed in the future.
