### ISSUE TITLE
WordPress 5 Editor Error with Shortcode [dwqa-submit-question-form]

### ISSUE THREAD

**Issue by STV11C** [designwall/dw-question-answer#234]
Hi all, please see attached screen shot of Page using shortcode **[dwqa-submit-question-form]**. The page links etc looks broken. If I rename the shortcode to anything else, save and refresh, all looks good. Rename back to original, save and refresh, broken again. It seems to be specifically with this shortcode. I've tested this on various environments and various themes, and the same problem persists. Strange.

<img width="684" alt="Capture" src="https://user-images.githubusercontent.com/5532744/65384579-3dd12f00-dd67-11e9-8bc0-f2fddb704c85.PNG">

**Comment by liuwanthang** [comment]
thank for your issue. I fixed it in new version.
