### ISSUE TITLE
adding composer-support

### ISSUE THREAD

**Issue by scheunemann** [designwall/dw-question-answer#44]
Hey there,

I would recommend composer support since it offers dependency management for PHP. More information can be found here:  https://github.com/composer/composer

I will add it to my fork.

**Comment by anna2810** [comment]
Hi Scheunemann,

Thank you for noticing us. We do really appreciate your help.

We have noted the issue you mentioned above. It will be fixed in the next version of DW Question & Answer. 

If there is any more issue with the plugin, please do not hesitate to get back to us. It encourages us a lot.
