### ISSUE TITLE
Missing "upload media" button in Ask question page if not yet register of log in

### ISSUE THREAD

**Issue by CarolHayes** [designwall/dw-question-answer#57]
- In case you are not yet log in or register, you can not see the media button to  upload image

![upload media button](https://cloud.githubusercontent.com/assets/6157366/2924119/f5659b1a-d728-11e3-97a9-e4079794128f.png)

**Comment by anna2810** [comment]
Hi CarolHayes,
Thank you for noticing us. We do really appreciate your help.

Currently, we have [DW TinyMCE Imgur Upload - WordPress Plugin](http://bit.ly/dw-tinymce-imgur-upload) to solve this problem. 

If there is any more issue with the plugin, please do not hesitate to get back to us. It encourages us a lot.
