### ISSUE TITLE
Missing " Upload media" in answer question form

### ISSUE THREAD

**Issue by CarolHayes** [designwall/dw-question-answer#58]
Logged in or not, can not see the upload media button in submit answer form 
![missing upload button in answer form](https://cloud.githubusercontent.com/assets/6157366/2924148/2cf1c83c-d72a-11e3-853e-dfdae0ad7444.png)

**Comment by anna2810** [comment]
Hi CarolHayes,
Thank you for noticing us. We do really appreciate your help.

Currently, we have [DW TinyMCE Imgur Upload - WordPress Plugin](bit.ly/dw-tinymce-imgur-upload) to solve this problem. 

If there is any more issue with the plugin, please do not hesitate to get back to us. It encourages us a lot.
