### ISSUE TITLE
The image link is truncated when insert media from URL 

### ISSUE THREAD

**Issue by CarolHayes** [designwall/dw-question-answer#61]
![truncated](https://cloud.githubusercontent.com/assets/6157366/2925583/9d66eb1e-d74e-11e3-97a0-50313f8bc617.png)

**Comment by anna2810** [comment]
Hi CarolHayes,
Thank you for noticing us. We do really appreciate your help.
This feature has been disabled in DWQA 1.4.0.
If there is any more issue with the plugin, please do not hesitate to get back to us. It encourages us a lot.
