### ISSUE TITLE
Votes and Display wp_send_json_error 

### ISSUE THREAD

**Issue by sgmg2007** [designwall/dw-question-answer#89]
First of all if user votes and he wants to cancel his votes he can't. He should either press up or down to change his vote( down or up). 
Second, If he tries to vote again in a question the wp_send_json_error does'nt do anything and I guess there should be a dialog to show $result['error_message'] ??

**Comment by anna2810** [comment]
Hi sgmg2007,

Thank you for noticing us. We do really appreciate your advice.

We will check and add this to the upcoming version of DW Q&A.

If there is any more issue with the plugin, please do not hesitate to get back to us. It encourages us a lot.
