### ISSUE TITLE
Voting, Answer, Follow, and other buttons do not seem to work (just click and nothing happens)?

### ISSUE THREAD

**Issue by gwfc** [designwall/dw-question-answer#97]
Hi:

Is there anyone out there who can help?

Voting, Answer, Follow, and other buttons do not seem to work (just click and nothing happens)?

**Comment by anna2810** [comment]
Hi Gwfc,

Thank you for noticing us. 

If there is any more issue with the DW Question & Answer, please do not hesitate to get back to us. It encourages us a lot.
